language: c

sudo: required

env:
  - TEST_SUITE=CRAN
  - TEST_SUITE=TRAVIS

before_install:
  - mkdir bin
  - pushd bin
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 *
  - export PATH=$(pwd):$PATH
  - popd
  - travis-tool.sh bootstrap
  - sudo apt-get install -y texlive
  - mkdir /tmp/tmp256K
  - sudo mount -t tmpfs -o size=256K tmpfs /tmp/tmp256K
  - mkdir /tmp/tmp160000
  - sudo mount -t tmpfs -o size=160000 tmpfs /tmp/tmp160000

install:
  - travis-tool.sh r_install devtools
  - travis-tool.sh install_deps
  - Rscript -e "devtools::install(dependencies=FALSE)"

script:
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

after_failure:
  - travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

